[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"

publish = false

[dependencies]
u8g2-fonts = { path = "../..", features = ["embedded_graphics_textstyle"] }
embedded-graphics-core = "0.4.0"
cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.6"
cortex-m-semihosting = "0.6.0"
panic-semihosting = { version = "0.7.0", features = ["exit"] }
crc = "3.4.0"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
