name: Check for new upstream font data
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0'
jobs:
  check_upstream_changes:
    name: Check upstream changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check if upstream changed the font file
        run: cd u8g2/ && git fetch && git diff origin/master HEAD -- csrc/u8g2_fonts.c
